version: '3.3'
services:
  books_db:
    build:
      context: .
      dockerfile: pgdockerfile
    container_name: books_db
    hostname: books_db
    environment:
      - POSTGRES_DB=books_db
      - POSTGRES_USER=guten
      - POSTGRES_PASSWORD=somepassword
      - PGDATA=/var/pgdata
    expose:
      - 5432
    ports:
      - "15432:5432"
    healthcheck:
      test: pg_isready -U guten -d books_db
      interval: 10s
      timeout: 3s
      retries: 3
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      books_db:
        condition: service_healthy
        required: true
    expose:
      - 8000
    ports:
      - "2332:8000"
    links:
      - books_db:books_db
    healthcheck:
      test: curl -f http://localhost:8000/healthcheck/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
